title: Novatype
description: Exploring the everchanging meanings of typography, across different
  periods of time.
footer_text: Copyright 2021 Thomas Stanier
header_feature_image: ../uploads/new-project-4-.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/new-project-7-.png
favicon: ../uploads/favicon.ico.ico
gridlayout: true
fixednavbar: false
upzoom: true
