title: Novatype
description: Exploring the past and future of typography.
footer_text: Copyright 2021 Thomas Stanier
header_feature_image: ../uploads/tumblr_890e0680b0b7511dbd92b73616a8cb09_93feef6b_1280.jpg
header_text: Typography
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
